sudo: required
language: go
global:
  env:
    - secure: OuxaxAgwVdorto2XXCm4mV42RNKP9hbGiozThH9W8tpvmwvRFrYf83FqPZf9HWCjLIxNDW22RenhNaYTP8neaxbDAxAuqD91YzL2VvTl7ta4I0sZbC7iNBNpIJ4r2ScG0Rhwb6R9d3VqyxySiXzuME2UxCv8956pd74EvALdIkT03nUfb9ti0nAEkffl4BxctkDBhnwfM/9YjbZQhdVwcPve1fS3hedRBfng4aFJ2PaE+QoC4ewSkfBARAHUdJXADtFTFBLQp+Q27WtBuJMLwOju5xIILWZl/Olp2w/PyYmLg3eT3Y2W1lMLSWobUnFyJgEGRbI8FBKg/ZxCMYVIE6aw/1rsh1rxJp/ZS9zIIF1fn74KUzGOx3gOzb51blI+RSreBMqu1dyHGPUD0yzetzOCrLUoXaVbSe3dEgQkYiqlMWH11B3fZQ4HyLWAF0TYavlHhrf31tg1HvjLnb9+jVoi/z1jZ3rvNtNCZnfbNMr9CfFeLRCn00DbxAaQZHe+k6TKw2G+GMuBmQVSMunHy6YM3qzJIw8UZIIkGwzXUzAxZiGWhpowoue2YI5Zokp85N+l1I6Wmfz7DSvzVFGjSsoNKE/PKhykx8ahi8xgjZg1ZnaUFosMe9hSXLkKhR1WhqObjd5DJtOPUJUiibj527TknCXUX7CtQ1EAnpXuG4g=
go:
  - 1.4
services:
  - redis-server
script: make test

after_success:
  - make install_equinox
  - make release
